---
title: "SQL Reading Group"
subtitle: "4-5pm Thursdays<br>B60 CB3"
toc: false
---

## Book

[SQL for Data Scientists](https://sqlfordatascientists.com/) by Renee Teate

* [PDF](https://onlinelibrary-wiley-com.libproxy.unl.edu/doi/book/10.1002/9781119669388)
* [HTML](https://learning.oreilly.com/library/view/sql-for-data/9781119669364/?sso_link=yes&sso_link_from=unl-edu)

## MySQL Installation and Farmer's Market Database

* [MySQL Documentation](https://dev.mysql.com/doc/refman/8.0/en/)
* Windows
  - [MySQL Community Installer](https://dev.mysql.com/downloads/installer/)
* MacOS
  - [MySQL Server](https://dev.mysql.com/downloads/mysql/) (install version 8.0.42)
  - [MySQL Community Workbench](https://dev.mysql.com/downloads/workbench/)
* [Farmer's Market Database](https://media.wiley.com/product_ancillary/67/11196693/DOWNLOAD/SQL%20for%20Data%20Scientists%20support%20files.zip)



## Schedule

| Meeting | Chapters |
|:--------|:---------|
| June 19 | 1: Data sources<br>2: SELECT |
| June 26 | 3: WHERE |
| July 3 | **NO MEETING**  |
| July 10 | 4: CASE<br>5: JOINS |
| July 17 | 6: Aggregating |
| July 24 | 7: Window functions |
| July 31 | 8: Date and time |
| August 7 |  9: Exploratory data analysis |
| August 14 | 10: Building datasets |
| August 21 | 11: Advanced query structures |

## Thought Questions/Exercises

<details>

<summary> Chapter 1: Data sources </summary>

1. How is a relational database different from a spreadsheet? How are they similar?
1. When would you want to store data in a relational database rather than a spreadsheet?
1. What is the difference between a database and a schema?
1. What is a primary key? What is a foreign key?
1. What is the primary key for the `customer` table? What about the `market_date_info` table? What about the `customer_purchases` table?
1. What are three foreign keys in the `customer_purchases` table?

</details>


<details>

<summary> Chapter 2: The SELECT Statement </summary>

1. What are the two functions/statements required for all SQL queries?
1. Are SQL functions/statements case sensitive? Try a query using `SELECT`, `select`, `Select`, and `sElEcT`. Do they all work?
1. What is the role of spaces, line breaks, and tabs in SQL queries?
1. What two pieces of information do you need to use the `FROM` statement?
1. What is the default sorting order for `ORDER BY`?
1. Which statement returns only first N rows, where the user can specify the number N?
1. When you use `ROUND` to round a column of numbers, does that change the values in the original table?
1. What happens if you concatenate two columns without specifying a delimiter?
1. Write a query that combines the three columns of `vendor_booth_assignments` separated by underscores to create a column that is a primary key. Name that column `key`.
</details>


<details>

<summary> Chapter 3: The WHERE Clause </summary>

1. Under what circumstances would you put quotes around a number?
1. Let's say your `WHERE` statement has three conditional statements. How many conditional statements have to be TRUE to keep a row when using `AND`? What about when using `OR`?
1. If you want to use a `WHERE` statement to subset rows for _customer_ids_ 3 and 4, which logical operator should you use?
1. How do we specify the order of operations for evaluating conditional statements?
1. Return a subset of the _customer_purchases_ table for transactions involving more than 15 items purchased.
1. Return a subset of the _customer_purchases_ for customer ids 2-5 using three different techniques.
1. Why does this statement not work? `WHERE customer_id = NULL`
1. What is a subquery?
</details>


<details>

<summary> Chapter 4: CASE Statements </summary>

1. What is feature engineering and why is it called that?
1. How do you return values that include specific character strings?
1. What happens to values that don't meet the conditions specified in `WHEN` statements if there is no `ELSE` provided?
1. What happens if a value in a column meets multiple `WHEN` conditional statements?
1. What column name is assigned if you don't assign a new column name with `AS`?
1. How can you create dummy variables with `CASE`?

</details>


<details>

<summary> Chapter 5: SQL JOINs </summary>

1. What does one-to-many mean in joins?
1. What does `LEFT` refer to in a `LEFT JOIN`?
1. How could we use `SELECT` to remove one of the duplicate column names for _product_category_id_ in Figure 5.5?
1. When using a `LEFT JOIN`, what happens if a key value in the left table does not have a corresponding key value in the right table?
1. What is table aliasing, and how do you use it?
1. How is an `INNER JOIN` different from a `LEFT JOIN` and `RIGHT JOIN`?
1. How many joins can you do at a time?

</details>


<details open>

<summary> Chapter 6: Aggregating Results for Analysis </summary>

1. Why was _vendor_id_ not included in the query generating Figure 6.6?
1. What is the difference between `COUNT` and `COUNT DISTINCT`?
1. Write a query that returns the earliest and latests transactions (using _transaction_time_) in the customer_purchases table.
1. Write a query that returns the earliest and latests transactions (using _transaction_time_) for each vendor in the customer_purchases table.
1. Write a query that returns the total number of different products for each vendor, along with the average quantity of items sold per vendor using the customer_purchases table.
1. What is the difference between `WHERE` and `HAVING`?
</details>


<details>

<summary> Chapter 7: Window Functions and Subqueries </summary>


</details>


<details>

<summary> Chapter 8: Date and Time Functions </summary>


</details>


<details>

<summary> Chapter 9: Exploratory Data Analysis with SQL </summary>


</details>


<details>

<summary> Chapter 10: Building SQL Datasets for Analytical Reporting </summary>


</details>


<details>

<summary> Chapter 11: More Advanced Query Structures </summary>


</details>


<details>

<summary> Chapter 12: Creating Machine Learning Datasets Using SQL </summary>


</details>


<details>

<summary> Chapter 13: Analytical Dataset Development Examples </summary>


</details>


<details>

<summary> Chapter 14: Storing and Modifying Data </summary>


</details>


