project:
  type: website
  render:
    - "*.qmd"
    - "!cv_old.qmd"
    - "!pubs.qmd"
    - "!test.qmd"

website:
  title: "Jeffrey R. Stevens"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
        - href: cv.qmd
          text: CV
        - href: publications.qmd
          text: Publications
        - href: people.qmd
          text: People
      - href: software.qmd
        text: Software
      - href: blog.qmd
        text: Blog
  google-analytics:
    tracking-id: "G-1P6FW90MJL"
    anonymize-ip: true
  cookie-consent: true


  page-footer:
    background: light
    left: "&copy; 2023 Jeffrey R. Stevens. Powered by <a href='https://www.quarto.org'>Quarto</a>."
    right:
      - icon: twitter
        href: https://twitter.com/JeffStevensADML
      - icon: mastodon
        href: https://fediscience.org/@JeffreyRStevens
      - icon: github
        href: https://github.com/JeffreyRStevens
      - icon: linkedin
        href: https://www.linkedin.com/in/JeffreyRStevens/
      - icon: envelope
        href: mailto:jeffrey.r.stevens@protonmail.com

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



