project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!cv_old.qmd"
    - "!pubs.qmd"
    - "!test.qmd"

website:
  title: "Jeffrey R. Stevens"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
        - href: cv.qmd
          text: CV
        - href: publications.qmd
          text: Publications
        - href: people.qmd
          text: People
      - href: software.qmd
        text: "R Resources"
      - href: blog.qmd
        text: Blog
  google-analytics:
    tracking-id: "G-1P6FW90MJL"
    anonymize-ip: true
  cookie-consent: true
  site-url: https://jeffreyrstevens.github.io/
  description: "Jeff Stevens' blog"


  page-footer:
    background: light
    left: "&copy; 2024 Jeffrey R. Stevens. Powered by <a href='https://www.quarto.org'>Quarto</a>."
    right:
      - icon: mastodon
        href: https://fediscience.org/@JeffreyRStevens
      - text: "{{< iconify fa6-solid square >}}"
        href: https://bsky.app/profile/jeffreyrstevens.bsky.social
      - icon: github
        href: https://github.com/JeffreyRStevens
      - icon: linkedin
        href: https://www.linkedin.com/in/JeffreyRStevens/
      - icon: envelope
        href: mailto:jeffrey.r.stevens@gmail.com

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



