---
title: "Jeffrey R. Stevens - Curriculum vitae"
date: "`r Sys.Date()`"
geometry:
  - right=1in
format:
  pdf: default
  html:
    css: flipmargin.css
    toc: true
    toc-location: left
---
\reversemarginpar

::: {.content-visible when-format="html"}
<p align="center"><a href="cv.pdf" class="btn btn-primary">PDF Version</a></p>
:::

 | 
-- | --
{{< fa envelope title="An envelope" >}} [jeffrey.r.stevens@protonmail.com](mailto:jeffrey.r.stevens@protonmail.com) |  [Open Science Framework](https://osf.io/4nx8b/">Open Science Framework)
{{< fa brands twitter title="Twitter logo" >}} [JeffStevensADML](http://twitter.com/JeffStevensADML) | [ORCiD](https://orcid.org/0000-0003-2375-1360)
{{< fa brands github title="GitHub logo" >}} [GitHub](http://github.com/jeffreyrstevens) | [Google Scholar](http://scholar.google.com/citations?hl=en&user=3KRfbWUAAAAJ)
{{< fa brands linkedin >}} [LinkedIn](https://www.linkedin.com/in/JeffreyRStevens/) | [ImpactStory](https://profiles.impactstory.org/u/0000-0003-2375-1360)


I'm Susan J. Rosowski Associate Professor of [Psychology](https://psychology.unl.edu) and a resident member of the [Center for Brain, Biology & Behavior](https://cb3.unl.edu/) at the [University of Nebraska-Lincoln](http://www.unl.edu/). I study decision making, cognition, and well-being in humans and other animals at the [Adaptive Decision Making Lab](https://decisionslab.unl.edu) and the [Canine Cognition and Human Interaction Lab](https://dogcog.unl.edu). I am also a Data Science Mentor at [RStudio Academy](https://www.rstudio.com/academy) where I teach data science to teams of learners.

## Professional Positions

[2003-2006]{.aside}

 NIH post-doctoral fellow, Dept. of Psychology, Harvard University, Cambridge, Massachusetts

[2006]{.aside}

 Lecturer, Dept. of Psychology, Harvard University, Cambridge, Massachusetts

[2006-2011]{.aside}

 Research scientist, Center for Adaptive Behavior and Cognition, Max Planck Institute for Human Development, Berlin, Germany

[2011-2017]{.aside}

 Assistant professor, Department of Psychology, University of Nebraska-Lincoln

[2012-]{.aside}

 Courtesy faculty, School of Biological Sciences, University of Nebraska-Lincoln

[2013-]{.aside}

 Resident faculty, Center for Brain, Biology & Behavior, University of Nebraska-Lincoln

[2017-]{.aside}

 Associate professor, Department of Psychology, University of Nebraska-Lincoln

[2020-]{.aside}
 
 Susan J. Rosowski associate professor, Department of Psychology, University of Nebraska-Lincoln

[2022-]{.aside}

 Data science mentor, [RStudio Academy](https://www.rstudio.com/academy)


## Education

[1992-1996]{.aside}

 __Baylor University__ B.S. Majors: Biology, Environmental Studies; Minor: Political Science (_Magna cum laude_)

[1997-2002]{.aside}

 __University of Minnesota__ Ph.D. Ecology, Evolution, and Behavior, Minor: Psychology (supervisor: David W. Stephens). Dissertation: _The behavioral ecology of food sharing_.


## Publications

\*undergraduate or graduate student author; \#invited journal article; PDFs and open, reproducible materials available [here](https://decisionslab.unl.edu/publications.html)

[1996]{.aside}

 Do, L.H., Gooch, R.D., **Stevens, J.R.**, & Holmes, W.C. (1996). New county records of *Botrychium lunarioides* in Texas. *American Fern Journal*, *86*, 28-31. [doi:10.2307/1547608](https://doi.org/10.2307/1547608)

 Holmes, W.C., Morgan, T.L., **Stevens, J.R.**, Gooch, R.D., & Singhurst, J.R. (1996). [Comments on the distribution of *Botrychium lunarioides* (Ophioglossaceae) in Texas.](http://www.biodiversitylibrary.org/item/47108)
*Phytologia*, *80*, 280-283.

 Morgan, T.L., **Stevens, J.R.**, & Holmes, W.C. (1996). [First report of *Wolffiella lingulata* (Lemnaceae) in western Mexico.](http://www.biodiversitylibrary.org/item/34588) *SIDA*, *17*, 289-290.

[2001]{.aside}

 Stephens, D.W. and **Stevens, J.R.** (2001). A simple spatially-explicit ideal-free distribution: A model and an experiment. *Behavioral Ecology and Sociobiology*, *49*, 220-234. [doi:10.1007/s002650000276](http://dx.doi.org/10.1007/s002650000276)

[2002]{.aside}

 Stephens, D.W., McLinn, C.M., & **Stevens, J.R.** (2002). Discounting and reciprocity in an Iterated Prisoner's Dilemma. *Science*, *298*, 2216-2218. [doi:10.1126/science.1078498](http://dx.doi.org/10.1126/science.1078498)

 **Stevens, J.R.** and Stephens, D.W. (2002). Food sharing: A model of manipulation by harassment. *Behavioral Ecology*, *13*, 393-400. [doi:10.1093/beheco/13.3.393](http://dx.doi.org/10.1093/beheco/13.3.393)

[2004]{.aside}

 **Stevens, J.R.** (2004). The selfish nature of generosity: Harassment and food sharing. *Proceedings of the Royal Society of London, Series B*, *271*, 451-456. [doi:10.1098/rspb.2003.2625](http://dx.doi.org/10.1098/rspb.2003.2625)

 **Stevens, J.R.** and \*Cushman, F.A. (2004). Cognitive constraints on reciprocity and tolerated scrounging. *Behavioral and Brain Sciences*, *27*, 569-570. [doi:10.1017/S0140525X04320121](http://dx.doi.org/10.1017/S0140525X04320121)

 **Stevens, J.R.** and Gilby, I.C. (2004). A conceptual framework for non-kin food sharing: Timing and currency of benefits. *Animal Behaviour*, *67*, 603-614. [doi:10.1016/j.anbehav.2003.04.012](http://dx.doi.org/10.1016/j.anbehav.2003.04.012)

 **Stevens, J.R.** and Hauser, M.D. (2004). Why be nice? Psychological constraints on the evolution of cooperation. *Trends in Cognitive Sciences*, *8*, 60-65. [doi:10.1016/j.tics.2003.12.003](http://dx.doi.org/10.1016/j.tics.2003.12.003)

 **Stevens, J.R.** and Stephens, D.W. (2004). The economic basis of cooperation: trade-offs between selfishness and generosity. *Behavioral Ecology*, *15*, 255-261. [doi:10.1093/beheco/arh006](http://dx.doi.org/10.1093/beheco/arh006)

[2005]{.aside}

 **Stevens, J.R.**, \*Cushman, F.A., and Hauser, M.D. (2005). Evolving the psychological mechanisms for cooperation. *Annual Review of Ecology, Evolution, and Systematics*, *36*, 499-518. [doi:10.1146/annurev.ecolsys.36.113004.083814](http://dx.doi.org/10.1146/annurev.ecolsys.36.113004.083814)

 **Stevens, J.R.**, \*Hallinan, E.V., and Hauser, M.D. (2005). The ecology and evolution of patience in two New World primates. *Biology Letters*, *1*, 223-226. [doi:10.1098/rsbl.2004.0285](http://dx.doi.org/10.1098/rsbl.2004.0285)

 **Stevens, J.R.** and Hauser, M.D. (2005). Cooperative brains: Psychological constraints on the evolution of altruism. In S. Dehaene, J.-R. Duhamel, M.D. Hauser, & L.G. Rizolatti (Eds.), [*From monkey brain to human brain*](http://cognet.mit.edu/book/monkey-brain-to-human-brain)
(pp. 159-187). Cambridge, MA: MIT Press.

 **Stevens, J.R.**, \*Rosati, A.G., \*Ross, K.R., and Hauser, M.D. (2005). Will travel for food: Spatial discounting and reward magnitude in two New World monkeys. *Current Biology*, *15*, 1855-1860. [doi:10.1016/j.cub.2005.09.016](http://dx.doi.org/10.1016/j.cub.2005.09.016)

[2006]{.aside}

 \*Rosati, A.G., **Stevens, J.R.**, and Hauser, M.D. (2006). The effect of handling time on temporal discounting in two New World primates. *Animal Behaviour*, *71*, 1379-1387. [doi:10.1016/j.anbehav.2005.11.012](http://dx.doi.org/10.1016/j.anbehav.2005.11.012)

 Stephens, D.W, McLinn, C.M., and **Stevens, J.R.** (2006). Effects of temporal clumping and payoff accumulation on impulsiveness and cooperation. *Behavioural Processes*, *71*, 29-40. [doi:10.1016/j.beproc.2005.09.003](http://dx.doi.org/10.1016/j.beproc.2005.09.003)

[2007]{.aside}

 \*Barton, A., Mousavi, S., and **Stevens, J.R.** (2007). A statistical taxonomy and another "chance" for natural frequencies. *Behavioral and Brain Sciences*, *30*, 255-256. [doi:10.1017/S0140525X07001665](http://doi.org/10.1017/S0140525X07001665)

 \*Rosati, A.G., **Stevens, J.R.**, Hare, B., and Hauser, M.D. (2007). The evolutionary origins of human patience: Temporal preferences in chimpanzees, bonobos, and human adults. *Current Biology*, *17*, 1663-1668. [doi:10.1016/j.cub.2007.08.033](http://doi.org/10.1016/j.cub.2007.08.033)

 **Stevens, J.R.**, \*Wood, J.N., and Hauser, M.D. (2007). Quantity trumps number: Discrimination experiments in cotton-top tamarins (*Saguinus oedipus*) and common marmosets (*Callithrix jacchus*). *Animal Cognition*, *10*, 429-437. [doi:10.1007/s10071-007-0081-8](http://doi.org/10.1007/s10071-007-0081-8)

[2008]{.aside}

 \*Heilbronner, S.R., \*Rosati, A.G., **Stevens, J.R.**, Hare, B., and Hauser, M.D. (2008). A fruit in the hand or two in the bush? Ecological pressures select for divergent risk preferences in chimpanzees and bonobos. *Biology Letters*, *4*, 246-249. [doi:10.1098/rsbl.2008.0081](http://doi.org/10.1098/rsbl.2008.0081)

 McElreath, R., Boyd, R., Gigerenzer, G., Glöckner, A., Hammerstein, P., Kurzban, R., Magen, S., Richerson, P., Robson, A., & **Stevens, J.R.** (2008). Individual decision making and the evolutionary roots of institutions. In C. Engel & W. Singer (Eds.), [*Better than conscious? Decision making, the human mind, and implications for institutions*](https://mitpress.mit.edu/books/better-conscious). Ernst Strüngmann Report 1. (pp. 325-342). Cambridge, MA: MIT Press.

 **Stevens, J.R.** (2008). The evolutionary biology of decision making. In C. Engel & W. Singer (Eds.), [*Better than conscious? Decision making, the human mind, and implications for institutions*](https://mitpress.mit.edu/books/better-conscious). Ernst Strüngmann Report 1. (pp. 285-304). Cambridge, MA: MIT Press.

 **Stevens, J.R.** & Stephens, D.W. (2008). Patience. *Current Biology*, *18*, R11-12. [doi:10.1016/j.cub.2007.11.021](http://doi.org/10.1016/j.cub.2007.11.021)

[2009]{.aside}

 \*Rosati, A.G. & **Stevens, J.R.** (2009). Rational decisions: The adaptive nature of context-dependence choice. In S. Watanabe, A.P. Blaisdell, L. Huber, & A. Young (Eds.), [*Rational animals, irrational humans*](https://www.keio-up.co.jp/kup/eng/bio/16150.html) (pp. 101-117). Tokyo: Keio University Press.

 **Stevens, J.R.** and Hauser, M.D. (2009). Social interaction effects on reward and cognitive abilities in monkeys. In L. Squire (Ed.), [*Encyclopedia of neuroscience*](https://booksite.elsevier.com/brochures/ens/) (pp. 45-58). Oxford: Academic Press.


 \*Straubinger, N. Cokely, E.T., and **Stevens, J.R.** (2009). The dynamics of development: Challenges for Bayesian rationality. Commentary in *Behavioral and Brain Sciences*, *32*, 103-104. [doi:10.1017/S0140525X09000491](http://doi.org/10.1017/S0140525X09000491)

[2010]{.aside}

 **Stevens, J.R.** (2010). The challenges of understanding animal minds. *Frontiers in Psychology*, *1*, 203. [doi:10.3389/fpsyg.2010.00203](https://doi.org/10.3389/fpsyg.2010.00203)

 **Stevens, J.R.** (2010). Donor payoffs and other-regarding preferences in cotton-top tamarins (*Saguinus oedipus*). *Animal Cognition*, *13*, 663-670. [doi:10.1007/s10071-010-0309-x](https://doi.org/10.1007/s10071-010-0309-x)

 **Stevens, J.R.** (2010). Intertemporal choice. In M. Breed & J. Moore (Eds.), [*Encyclopedia of animal behavior*](https://www.elsevier.com/books/encyclopedia-of-animal-behavior/breed/978-0-08-045333-0) (Vol. 2, pp. 203-208). Oxford: Academic Press.

 **Stevens, J.R.** (2010). Rational decision making in primates: The bounded and the ecological. In M.L. Platt & A.A. Ghazanfar (Eds.), *Primate neuroethology* (pp. 98-116). Oxford: Oxford University Press. [doi:10.1093/acprof:oso/9780195326598.003.0006](https://doi.org/10.1093/acprof:oso/9780195326598.003.0006)

 **Stevens, J.R.** & Stephens, D.W. (2010). The adaptive nature of impulsivity. In G.J. Madden & W.K. Bickel (Eds.), *Impulsivity: The behavioral and neurological science of discounting* (pp. 361-387). Washington, D.C.: APA Press. [doi:10.1037/12069-013](https://doi.org/10.1037/12069-013)

[2011]{.aside}

 \*Mühlhoff, N., **Stevens, J.R.** & Reader, S.M. (2011). Spatial discounting of food and social rewards in guppies (*Poecilia reticulata*). *Frontiers in Psychology*, *2*, 68. [doi:10.3389/fpsyg.2011.00068](http://doi.org/10.3389/fpsyg.2011.00068)

 Seed, A., Clayton, N., Carruthers, P., Dickinson, A., Glimcher, P.W., Güntürkün, O., Hampton, R.R., Kacelnik, A., Shanahan, M.,**Stevens, J.R.** & Tebbich, S. (2011). Planning, memory, and decision making. In R. Menzel & J. Fischer (Eds.), [*Animal thinking: Contemporary issues in comparative cognition*](https://mitpress.mit.edu/books/animal-thinking). Ernst Strüngmann Forum Report (vol. 8, pp. 121-147). Cambridge, MA: MIT Press.

 **Stevens, J.R.** (2011). Mechanisms for decisions about the future. In R. Menzel & J. Fischer (Eds.), [*Animal thinking: Contemporary issues in comparative cognition*](https://mitpress.mit.edu/books/animal-thinking). Ernst Strüngmann Forum Report (vol. 8, pp. 93-104). Cambridge, MA: MIT Press.

 \#**Stevens, J.R.**, \*Rosati, A.G., \*Heilbronner, S.R., & \*Mühlhoff, N. (2011). Waiting for grapes: Expectancy and delayed gratification in bonobos. *International Journal of Comparative Psychology*. *24*, 99-111. [https://escholarship.org/uc/item/4km2r37j](https://escholarship.org/uc/item/4km2r37j)

 **Stevens, J.R.**, \*Volstorf, J., Schooler, L.J., & Rieskamp, J. (2011). Forgetting constrains the evolution of cooperative decision strategies. *Frontiers in Psychology*, *1*, 235. [doi:10.3389/fpsyg.2010.00235](http://doi.org/10.3389/fpsyg.2010.00235)

 \*Volstorf, J., Rieskamp, J. & **Stevens, J.R.** (2011). The good, the bad, and the rare: Memory for partners in social interactions. *PLoS ONE*, *6*, e18945. [doi:10.1371/journal.pone.0018945](http://doi.org/10.1371/journal.pone.0018945)

[2012]{.aside}

 \*Artinger, F., \*Fleischhut, N., Levanti, V., & **Stevens, J.R.** (2012). [Cooperation in risky environments: decisions from experience in a stochastic social dilemma](https://cogsci.mindmodeling.org/2012/papers/0028/paper0028.pdf). *Proceedings of the 34th Conference of the Cognitive Science Society* (pp. 84-89). Austin, TX: Cognitive Science Society.

 Gluck, K.A., McNamara, J.M., Brighton, H., Dayan, P., Kareev, Y., Krause, J., Kurzban, R., Selten, R., **Stevens, J.R.**, Voelkl, B., & Wimsatt, W.C. (2012). Robustness in a variable environment. In P. Hammerstein & J.R. Stevens (Eds.), [*Evolution and the mechanisms of decision making*](https://mitpress.mit.edu/books/evolution-and-mechanisms-decision-making). Ernst Strüngmann Forum Report (vol. 11, pp. 195-214). Cambridge, MA: MIT Press.

 Hammerstein, P., & **Stevens, J.R.** (2012). [*Evolution and the mechanisms of decision making*](https://mitpress.mit.edu/books/evolution-and-mechanisms-decision-making). Ernst Strüngmann Forum Report (vol. 11). Cambridge, MA: MIT Press.

 Hammerstein, P., & **Stevens, J.R.** (2012). Six reasons to evoke evolution in decision theory. In P. Hammerstein & J.R. Stevens (Eds.), [*Evolution and the mechanisms of decision making*](https://mitpress.mit.edu/books/evolution-and-mechanisms-decision-making). Ernst Strüngmann Forum Report (vol. 11, pp. 1-17). Cambridge, MA: MIT Press.

 Stevens, A.N.P. & **Stevens, J.R.** (2012). [Animal cognition](http://www.nature.com/scitable/knowledge/library/animal-cognition-96639212). *Nature Education Knowledge*, *3*, 1.

 \#**Stevens, J.R.** & \*Mühlhoff, N. (2012). Intertemporal choice in lemurs. *Behavioural Processes*, *89*, 121-127. [doi:10.1016/j.beproc.2011.10.002](http://doi.org/10.1016/j.beproc.2011.10.002)

[2013]{.aside}

 \#Kaighobadi, F. & **Stevens, J.R.** (2013). Does fertility status influence impulsivity and risk taking in human females? Adaptive influences on intertemporal choice and risky decision making. *Evolutionary Psychology*, *11*, 700-717. [doi:10.1177/147470491301100314](http://doi.org/10.1177/147470491301100314)

 Pachur, T., Schooler, L.J., & **Stevens, J.R.** (2013). When will we meet again? Regularities of social connectivity and their reflections in memory and decision making. In: R. Hertwig, U. Hoffrage, & the ABC Research Group (Eds.), *Simple heuristics in a social world* (pp. 199-224). Oxford: Oxford University Press. [10.1093/acprof:oso/9780195388435.003.0007](https://doi.org/10.1093/acprof:oso/9780195388435.003.0007)

 \#**Stevens, J.R.** (2013). The bounds of rationality and cognitive building blocks. *Behavioral Ecology*, *24*, 13-14. [doi:10.1093/beheco/ars089](http://doi.org/10.1093/beheco/ars089)

 **Stevens, J.R.** & King, A.J. (2013). The lives of others: Social rationality in animals. In: R. Hertwig, U. Hoffrage, & the ABC Research Group (Eds.), *Simple heuristics in a social world* (pp. 409-431). Oxford: Oxford University Press. [10.1093/acprof:oso/9780195388435.003.0015](https://doi.org/10.1093/acprof:oso/9780195388435.003.0015)

 \#**Stevens, J.R.**, Pachur, T., & Schooler, L. J. (2013). Rational analysis of the adaptive and predictive nature of memory. *Journal of Applied Research in Memory and Cognition*, *2*, 251-253. [doi:10.1016/j.jarmac.2013.10.006](http://doi.org/10.1016/j.jarmac.2013.10.006)

[2014]{.aside}

 **Stevens, J.R.** (2014). Evolutionary pressures on primate intertemporal choice. *Proceedings of the Royal Society of London, Series B*, *281*, 20140499. [doi:10.1098/rspb.2014.0499](http://doi.org/10.1098/rspb.2014.0499)

 Pachur, T., Schooler, L.J., & **Stevens, J.R.** (2014). We'll meet again: Revealing distributional and temporal patterns of social contact. *PLoS ONE*, *9*, e86081. [doi:10.1371/journal.pone.0086081](http://doi.org/10.1371/journal.pone.0086081)

[2015]{.aside}

 Barron, A.B., Hebets, E.A., Cleland, T.A., Fitzpatrick, C.L., Hauber, M.E., & **Stevens, J.R.** (2015). Embracing multiple definitions of learning. *Trends in Neurosciences*, *38*, 405-407. [doi:10.1016/j.tins.2015.04.008](http://doi.org/10.1016/j.tins.2015.04.008)

[2016]{.aside}

 \*Duque, J.F. & **Stevens, J.R.** (2016). Voluntary food sharing in pinyon jays: The role of reciprocity and dominance. *Animal Behaviour*, *122*, 135--144. [doi:10.1016/j.anbehav.2016.09.020](http://doi.org/10.1016/j.anbehav.2016.09.020)

 Mendelson, T.C., Fitzpatrick, C.L., Hauber, M.E., Pence, C.H., Rodríguez, R.L., Safran, R.J., \*Stern, C.A., **Stevens, J.R.** (2016). Cognitive phenotypes and the evolution of animal decisions. *Trends in Ecology and Evolution*, *31*, 850-859. [doi:10.1016/j.tree.2016.08.008](http://doi.org/10.1016/j.tree.2016.08.008)

 **Stevens, J.R.** (2016). Intertemporal similarity: Discounting as a last resort. *Journal of Behavioral Decision Making*, *29*, 12-24. [doi:10.1002/bdm.1870](http://doi.org/10.1002/bdm.1870)

 **Stevens, J.R.**, \*Kennedy, B.A., \*Morales, D., & Burks, M. (2016). The domain specificity of intertemporal choice in pinyon jays. *Psychonomic Bulletin & Review*, *23*, 915-921. [doi:10.3758/s13423-015-0973-6](http://doi.org/10.3758/s13423-015-0973-6)

 **Stevens, J.R.** & \*Duque, J. (2016). Psychology of reciprocal altruism. In: T.K. Shackelford & V.A. Weekes-Shackelford (Eds.), *Encyclopedia of evolutionary psychological science* (pp. 1-9). New York: Springer. [doi:10.1007/978-3-319-16999-6_3051-1](http://doi.org/10.1007/978-3-319-16999-6_3051-1)

 **Stevens, J.R.**, Marewski, J.N., Schooler, L.J., & Gilby, I.C. (2016). Reflections of the social environment in chimpanzee memory: Applying rational analysis beyond humans. *Royal Society Open Science*, *3*, 160293. [doi:10.1098/rsos.160293](http://doi.org/10.1098/rsos.160293)

[2017]{.aside}

 \*Duque, J.F. & **Stevens, J.R.** (2017). Cylinder task. In: J. Vonk & T.K. Shackelford (Eds.), *Encyclopedia of animal cognition and behavior*. New York: Springer. [doi:10.1007/978-3-319-47829-6_1608-1](http://doi.org/10.1007/978-3-319-47829-6_1608-1)

 **Stevens, J.R.** (2017). Intertemporal choice and delayed gratification. In: J. Call (Ed.), *APA handbook of comparative psychology* (pp. 535-552). Washington, DC: American Psychological Association. [doi:10.1037/0000012-024](http://doi.org/10.1037/0000012-024)

 **Stevens, J.R.** (2017). [*Impulsivity: How risk and time influence decision making*](https://www.springer.com/us/book/9783319517209). New York: Springer.

 **Stevens, J.R.** (2017). The many faces of impulsivity. In J.R. Stevens (Ed.) *Impulsivity: How risk and time influence decision making*. New York: Springer. [doi:10.1007/978-3-319-51721-6_1](http://doi.org/10.1007/978-3-319-51721-6_1)

 **Stevens, J.R.** (2017). Replicability and reproducibility in comparative psychology. *Frontiers in Psychology*, 8, 862. [doi:10.3389/fpsyg.2017.00862](http://doi.org/10.3389/fpsyg.2017.00862)

 \*Winke, T. & **Stevens, J.R.** (2017). Is cooperative memory special? The role of costly errors, context, and social network size when remembering cooperative actions. *Frontiers in Robotics and AI*, 4, 52. [doi:10.3389/frobt.2017.00052](http://doi.org/10.3389/frobt.2017.00052)

[2018]{.aside}

 \*Duque, J.F., \*Leichner, W., \*Ahmann, H. & **Stevens, J.R.** (2018). Mesotocin influences pinyon jay prosociality. *Biology Letters*, 14(4), 20180105. [doi:10.1098/rsbl.2018.0105](http://doi.org/10.1098/rsbl.2018.0105)

 Regenwetter, M., Cavagnaro, D., \*Popova, A., \*Guo, Y., \*Zwilling, C., Lim, S.-H., & **Stevens, J.R.** (2018). Heterogeneity and parsimony in intertemporal choice. *Decision*, 5(2), 63-94. [doi:10.1037/ dec0000069](http://doi.org/10.1037/dec0000069)

 **Stevens, J.R.** & Soh, L.-K. (2018). Predicting similarity judgments in intertemporal choice with machine learning. *Psychonomic Bulletin & Review*, 25(2), 627--635.
[doi:10.3758/s13423-017-1398-1](https://doi.org/10.3758/s13423-017-1398-1)

 **Stevens, J.R.**, Woike, J., Schooler, L.J., \*Lindner, S., and Pachur, T. (2018) Social contact patterns can buffer costs of forgetting in the evolution of cooperation. *Proceedings of the Royal Society of London, Series B*, 285(1880), 20180407. [doi:10.1098/rspb.2018.0407](https://doi.org/10.1098/rspb.2018.0407)

[2019]{.aside}

 Koehler, K., Boron, J.B., Garvin, T.M., Bice, M.R., & **Stevens, J.R.** (2019). Differential relationship between physical activity and intake of added sugar and nutrient-dense foods: A cross-sectional analysis. *Appetite*, 120, 91-97. [doi:10.1016/j.appet.2019.05.010](https://doi.org/10.1016/j.appet.2019.05.010)

 **Stevens, J.R.** & \*Duque, J.F. (2019). Order matters: Alphabetizing in-text citations biases citation rates. *Psychonomic Bulletin & Review*, 26(3), 1020-1026. [doi:10.3758/s13423-018-1532-8](https://doi.org/10.3758/s13423-018-1532-8)

 \*Thayer, E. & **Stevens, J.R.** (2019). Animal-assisted intervention. In: J. Vonk & T.K. Shackelford (Eds.), *Encyclopedia of animal cognition and behavior*. New York: Springer. [doi:10.1007/10.1007/978-3-319-47829-6_2057-1](https://doi.org/10.1007/978-3-319-47829-6_2057-1)

 \*Thayer, E. & **Stevens, J.R.** (2019). Human-animal interaction. In: J. Vonk & T.K. Shackelford (Eds.), *Encyclopedia of animal cognition and behavior*. New York: Springer. [doi:10.1007/978-3-319-47829-6_2058-1](https://doi.org/10.1007/978-3-319-47829-6_2058-1)

[2020]{.aside}

 \#Duque, J.F., \*Rasmussen, T., \*Rodriguez, A., & **Stevens, J.R.** (2020). The role of mesotocin on social bonding in pinyon jays. *Ethology*, 126(2), 165-175. [doi:10.1111/eth.12990](https://doi.org/10.1111/eth.12990)

 \*Arce, W. & **Stevens, J.R.** (2020). Developing a computer-controlled treat dispenser for canine operant conditioning. *Journal of Open Hardware*, 4(1), 6. [doi:10.5334/joh.27](https://doi.org/10.5334/joh.27)

[2021]{.aside}

 \#Addessi, E., \*Tierno, V., \*Focaroli, V., \*Rossi, F., \*Gastaldi, S., \*De Petrillo, F., Paglieri, F., & **Stevens, J.R.** (2021). Are capuchin monkeys (*Sapajus spp.*) sensitive to lost opportunities? The role of opportunity costs in intertemporal choice. *Philosophical Transactions of the Royal Society B: Biological Sciences*, 376(1819), 20190674. [doi:10.1098/rstb.2019.0674](https://doi.org/10.1098/rstb.2019.0674) 

 \#Goh, F. & **Stevens, J.R.** (2021). Attribute-based choice. In: R. Viale (Ed.), *Routledge handbook of bounded rationality*. (pp. 242-253). Routledge. [doi:10.4324/9781315658353-16](https://doi.org/10.4324/9781315658353-16) 

 Koehler, K., \*Beckford, S. E., \*Thayer, E., \*Martin, A.R., Boron, J. B., & **Stevens, J. R.** (2021). Exercise shifts hypothetical food choices towards greater amounts and more immediate consumption. *Nutrients*, 13(2), 347. [doi:10.3390/nu13020347](https://doi.org/10.3390/nu13020347) 

 Schutte, A., Torquati, J., & **Stevens, J.R.** (2021). *Nature and Psychology: Biological, Cognitive, Developmental, and Social Pathways to Well-Being*. New York: Springer. [doi:10.1007/978-3-030-69020-5](https://doi.org/10.1007/978-3-030-69020-5) 

 Schutte, A., Torquati, J., & **Stevens, J.R.** (2021). Introduction. In: A. Schutte, J. Torquati, & J.R. Stevens. *Nature and Psychology: Biological, Cognitive, Developmental, and Social Pathways to Well-Being*. New York: Springer. [doi:10.1007/978-3-030-69020-5_1](https://doi.org/10.1007/978-3-030-69020-5_1) 

 **Stevens, J. R.**, (2021). excluder: An R package that checks for exclusion criteria in online data. *Journal of Open Source Software*, 6(67), 3893, [doi:10.21105/joss.03893](https://doi.org/10.21105/joss.03893) 

 **Stevens, J.R.**, \*Saltzman, A., \*Rasumussen, T., & Soh, L.-K. (2021). Improving measurements of similarity judgments with machine-learning algorithms. *Journal of Computational Social Science*, 4(2), 613-629. [doi:10.1007/s42001-020-00098-1](https://doi.org/10.1007/s42001-020-00098-1) 

 **Stevens, J.R.**, \*Wolff, L.M., \*Bosworth, M., & Morstad, J. (2021). Dog and owner characteristics predict obedience and impulsivity. *Animal Cognition*, 24(2) 219-230. [doi:10.1007/s10071-020-01458-0](https://doi.org/10.1007/s10071-020-01458-0)

 \*Thayer, E.R. & **Stevens, J.R.** (2021). Effects of human-animal interactions on affect and cognition. *Human-Animal Interaction Bulletin*, 10(2), 73-98. [preprint at *PsyArXiv*](https://doi.org/10.31234/osf.io/7v5nq)

[2022]{.aside}

 \*Arce, W. & **Stevens, J. R.** (2022). A precise dispenser design for canine cognition research. *Journal of Open Hardware*, 6(1) 2. [doi:10.5334/joh.41](https://doi.org/10.5334/joh.41) 

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/arce_stevens_2022.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://decisionslab.unl.edu/data/arce_stevens_2022_data.csv" title="Data" class="cv-pub-links">Data</a>
<a href="https://decisionslab.unl.edu/data/arce_stevens_2022_rcode.R" title="Code" class="cv-pub-links">Code</a>
<a href="https://www.youtube.com/watch?v=fIKlNvzwXUY" title="Video" class="cv-pub-links">Video</a>
<a href="https://hackaday.com/2022/02/06/open-hardware-dog-treat-dispenser-is-a-stepping-stone-for-behavioral-research/" title="Press" class="cv-pub-links">Press</a>
<a href="https://github.com/unl-cchil/canine_precise_dispenser" title="GitHub" class="cv-pub-links">GitHub</a>
:::

 Bryer, M. A. H., Koopman, S. E., Cantlon, J. F., Piantadosi, S. T., MacLean, E. L., Baker, J. M., Beran, M. J., Jones, S. M., Jordan, K. E., Mahamane, S., Nieder, A., Perdue, B. M., Range, F., **Stevens, J. R.**, Tomonaga, M., Ujfalussy, D. J., & Vonk, J. (2022). The evolution of quantitative sensitivity. *Philosophical Transactions of the Royal Society B: Biological Sciences*, 377(1844), 20200529. [doi:10.1098/rstb.2020.0529](https://doi.org/10.1098/rstb.2020.0529) 
 
::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/bryer_etal_2022.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://decisionslab.unl.edu/pubs/bryer_etal_2022_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a>
<a href="https://osf.io/j9sv8/" title="Data & code" class="cv-pub-links">Data & code</a>
:::

 \*Goh, F., \*Jungck, A.C., & **Stevens, J.R.** (2022). Pro tip: Screen-based payment methods increase negative feelings in consumers but do not increase tip sizes. [doi:10.33422/ejbs.v4i4.678](https://doi.org/10.33422/ejbs.v4i4.678) 

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/goh_etal_2022_preprint.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://decisionslab.unl.edu/pubs/goh_etal_2022_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a>
<a href="https://osf.io/bqf52/" title="Data, code, reproducible materials" class="cv-pub-links">Data & code</a>
<a href="https://psyarxiv.com/yfne8" title="Preprint" class="cv-pub-links">Preprint</a>
:::


 Miller, R., Lambert, M. L., Frohnwieser, A., Brecht, K. F., Bugnyar, T., Crampton, I., Garcia-Pelegrin, E., Gould, K., Greggor, A. L., Izawa, E.-I., Kelly, D. M., Li, Z., Luo, Y., Luong, L. B., Massen, J. J. M., Neider, A., Reber, S. A., Schiestl, M., Seguchi, A., **Stevens, J.R.**, Taylor, A.H., Wang, L.,  Wolff, L.M.,  Zhang, Y., Clayton, N. S. (2022). Socio-ecological correlates of neophobia in corvids. *Current Biology*, 32(1), 74-85.e4.  [doi:10.1016/j.cub.2021.10.045](https://doi.org/10.1016/j.cub.2021.10.045) 

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/miller_etal_2021_preprint.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://decisionslab.unl.edu/pubs/miller_etal_2021_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a>
<a href="https://decisionslab.unl.edu/data/miller_etal_2021_data.csv" title="Data" class="cv-pub-links">Data</a>
<a href="https://decisionslab.unl.edu/data/miller_etal_2021_rcode.R" title="Code" class="cv-pub-links">Code</a>
<a href="https://www.youtube.com/watch?v=Lhzyk3srmdg" title="Video" class="cv-pub-links">Video</a>
<a href="https://news.unl.edu/newsrooms/today/article/boo-birds-worldwide-study-finds-differences-in-avian-fear-of-the-unknown/" title="Press" class="cv-pub-links">Press</a>
<a href="https://doi.org/10.1101/2021.07.27.453788" title="Preprint" class="cv-pub-links">Preprint</a>
:::

 \*Marvin, S., \*Sorenson, K., & **Stevens, J. R.** (2022). Bringing human-animal interaction to sport: Potential impacts on athletic performance. *European Journal of Sport Science*, 22(7), 955-963. [doi:10.1080/17461391.2021.1916084](https://doi.org/10.1080/17461391.2021.1916084) 

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/marvin_etal_2020_preprint.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://psyarxiv.com/w4p7b" title="Preprint" class="cv-pub-links">Preprint</a>
:::

 **Stevens, J.R.**, \*Mathias, M., \*Herridge, M., \*Hughes-Duvall, K., \*Wolff, L. M., & \*Yohe, M. (2022). Do owners know how impulsive their dogs are? *Animal Behavior & Cognition*,   9(3), 261-286. [doi:10.26451/abc.09.03.02.2022](https://doi.org/10.26451/abc.09.03.02.2022)
 <!-- [[PDF](https://decisionslab.unl.edu/pubs/stevens_etal_2022.pdf)] -->

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/stevens_etal_2022.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://decisionslab.unl.edu/pubs/stevens_etal_2022_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a>
<a href="https://osf.io/eb5m3/" title="Data, code, reproducible materials" class="cv-pub-links">Data & code</a>
<a href="https://psyarxiv.com/hyvdq" title="Preprint" class="cv-pub-links">Preprint</a>
:::


<!-- Forthcoming -->
[Preprints]{.aside}

 \*Goh, F. & **Stevens, J.R.** (2022). 	Social influences on similarity judgments and intertemporal choice. _PsyArXiv_. [doi:10.31234/osf.io/xz68b](https://doi.org/10.31234/osf.io/xz68b) 

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/goh_stevens_2022.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://decisionslab.unl.edu/pubs/goh_stevens_2022_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a>
<a href="https://osf.io/du2xm/" title="Data, code, reproducible materials" class="cv-pub-links">Data & code</a>
<a href="https://psyarxiv.com/xz68b" title="Preprint" class="cv-pub-links">Preprint</a>
:::

 Höchsmann, C., Becksford, S.E., French, J.A., Boron, J.B., **Stevens, J.R.**, & Koehler, K. (2022). Biological and behavioral predictors of compensatory energy intake after exercise. *Research Square* [doi:10.21203/rs.3.rs-1414640/v1](https://doi.org/10.21203/rs.3.rs-1414640/v1) 

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/hochsmann_etal_2022_preprint.pdf" title="PDF" class="cv-pub-links">PDF</a>
:::

 ManyDogs Project, Alberghina, D., Bray, E., Buchsbaum, D., Byosiere, S.-E., Espinosa, J., Gnanadesikan, G., Guran, C.-N.A., Hare, E., Horschler, D., Huber, L., Kuhlmeier, V.A., MacLean, E., Pelgrim, M.H., Perez, B., Ravid-Schurr, D., Rothkoff, L., Sexton, C., Silver, Z., & **Stevens, J.R.** (2022). ManyDogs Project: A big team science approach to investigating canine behavior and cognition. _PsyArXiv_. [doi:10.31234/osf.io/j82uc](https://doi.org/10.31234/osf.io/j82uc).

::: {.content-visible when-format="html"}
<a href="https://doi.org/10.31234/osf.io/j82uc" title="Preprint" class="cv-pub-links">Preprint</a>
:::

 ManyDogs Project, Espinosa, J., Bray, E., Buchsbaum, D., Byosiere, S.-E., Byrne, M., Freeman, M. S., Gnanadesikan, G., Guran, C.-N. A., Horschler, D., Huber, L., Johnston, A., MacLean, E., Pelgrim, M. H., Santos, L., Silver, Z. A., **Stevens, J. R.**, Völter, C., & Zipperling, L. (2021). ManyDogs 1: A multi-lab replication study of dogs’ pointing comprehension. Stage 1 registered report at *Animal Behavior & Cognition*. [doi:10.31234/osf.io/f86jq](https://doi.org/10.31234/osf.io/f86jq) 
 
::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/manydogs_2021_preprint.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://psyarxiv.com/f86jq" title="Preprint" class="cv-pub-links">Preprint</a>
:::

 **Stevens, J.R.** (2022). flashr: An R package that creates flashcards. _OSF Preprints_. [doi:10.31219/osf.io/w7dks](https://doi.org/10.31219/osf.io/w7dks).
 
::: {.content-visible when-format="html"}
<a href="https://osf.io/w7dks/" title="Preprint" class="cv-pub-links">Preprint</a>
:::

**Stevens, J.R.**, \*Cully, T., & \*Goh, F.W. (2021). Framing attributes in similarity judgments and intertemporal choices. _PsyArXiv_. [doi:10.31234/osf.io/csnqv](https://doi.org/10.31234/osf.io/csnqv) 

::: {.content-visible when-format="html"}
<a href="https://decisionslab.unl.edu/pubs/stevens_etal_2021.pdf" title="PDF" class="cv-pub-links">PDF</a>
<a href="https://decisionslab.unl.edu/pubs/stevens_etal_2021_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a>
<a href="https://osf.io/xnwra/" title="Data, code, reproducible materials" class="cv-pub-links">Data & code</a>
<a href="https://psyarxiv.com/csnqv" title="Preprint" class="cv-pub-links">Preprint</a>
:::

\*Wolff, L. M., \*Carey, K., \& **Stevens, J.R.** (2022). Friends aren’t food: pinyon jays show context-dependent numerical cognition. _PsyArXiv_. [doi:10.31234/osf.io/kxgwt](https://doi.org/10.31234/osf.io/kxgwt)

::: {.content-visible when-format="html"}
<!-- <a href="https://decisionslab.unl.edu/pubs/wolff_etal_2022.pdf" title="PDF" class="cv-pub-links">PDF</a> -->
<!-- <a href="https://decisionslab.unl.edu/pubs/wolff_etal_2022_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a> -->
<a href="https://osf.io/g45nk/" title="Data, code, reproducible materials" class="cv-pub-links">Data & code</a>
<a href="https://psyarxiv.com/kxgwt" title="Preprint" class="cv-pub-links">Preprint</a>
:::

<!-- ::: {.content-visible when-format="html"} -->
<!-- <a href="https://decisionslab.unl.edu/pubs/stevens_etal_2021.pdf" title="PDF" class="cv-pub-links">PDF</a> -->
<!-- <a href="https://decisionslab.unl.edu/pubs/stevens_etal_2021_SM.pdf" title="Supplementary Materials" class="cv-pub-links">SM</a> -->
<!-- <a href="https://osf.io/qv542/" title="Data" class="cv-pub-links">Data</a> -->
<!-- <a href="https://osf.io/gdhf8/" title="R code" class="cv-pub-links">R Code</a> -->
<!-- <a href="data/stevens_etal_2021_rr.zip" title="Reproducible materials" class="cv-pub-links">Reproducible materials</a> -->
<!-- <a href="https://osf.io/xnwra/" title="OSF" class="cv-pub-links">OSF</a> -->
<!-- <a href="https://psyarxiv.com/csnqv" title="PsyArXiv" class="cv-pub-links">PsyArXiv</a> -->
<!-- :::  -->


## Presentations

### Invited

[2003]{.aside}

 "The behavioral ecology of food sharing", Dept. of Psychology, University of Pennsylvania

[2004]{.aside}

 "Selfish minds: psychological constraints on the evolution of animal cooperation", Dept. of Psychology, University of New Hampshire

 "Temporal discounting and cooperation in non-human animals", Advances in Economics and Biology, Toulouse, France

 "Selfish minds: psychological constraints on the evolution of cooperation", Cognition, Brain, and Behavior Group, Dept. of Psychology, Harvard University

[2005]{.aside}

 "Rational minds: the psychology and ecology of animal decision making", Center for Ecology and Conservation Biology, Boston University

 "Rational minds: the psychology and ecology of animal decision making", Dept. of Developmental and Comparative Psychology, Max Planck Institute for Evolutionary Anthropology, Leipzig, Germany

[2006]{.aside}

 "Temporal discounting and aging", MaxnetAging Conference, Naples, Italy

 "Evolving the psychological mechanisms for cooperation", Dept. of Behavioral Ecology, University of Bern, Switzerland

[2007]{.aside}

 "The evolution of patience: temporal preferences in humans and other animals", Max Planck Society PhDNet Conference, Berlin, Germany

 "The evolution of primate patience", Dept. of Zoology, Oxford University

 "Rational minds: economic decision making in animals", Ape Economics Conference, Max Planck Institute for Evolutionary Anthropology, Leipzig, Germany

 "The evolutionary origins of patience", Dept. of Biology, Humboldt University, Berlin, Germany

[2008]{.aside}

 "The bounded rationality of cooperation", Wenner-Gren Symposium on Human Evolution, Stockholm, Sweden

 "The evolution of patience", Max Planck Institute for Molecular Genetics Retreat, Berlin, Germany

 "The bounded rationality of cooperation", Evolution of Cognition and Evolution of Cooperation Workshop, Provence, France

 "The evolution of patience: temporal preferences in primates", Max Planck Institute for Ornithology, Seewiesen, Germany

[2009]{.aside}

 "The bounded rationality of cooperation", Dept. of Cognitive Biology, University of Vienna, Austria

 "The bounded rationality of self-control", Evolution and Human Adaptation Program, University of Michigan

 "The bounded rationality of cooperation", Workshop on Social Interactions, University of Neuchâtel, Switzerland

[2010]{.aside}

 "The bounded rationality of cooperation", Department of Psychology, University of Basel, Switzerland

 "The ecological rationality of patience", Institute for Cognitive Science and Technologies, Consiglio Nazionale delle Ricerche, Rome, Italy

 "The bounded rationality of cooperation", Research Center on Animal Cognition, Université Paul Sabatier, Toulouse, France

 "Darwinian decisions: the psychology and evolution of decision making", Zoological Society of London's Communicating Science series, London

 "The bounded rationality of cooperation", Workshop on Avoiding Tragedies of the Commons, University of Neuchâtel, Switzerland

[2011]{.aside}

 "The ecological rationality of patience", CompCog Conference, Prague, Czech Republic

 "The bounded rationality of cooperation", Faculty of Biology, University of Lausanne, Switzerland

[2012]{.aside}

 "Cognition and the evolution of cooperation", Social Structure Summer School, Göttingen, Germany

 "The cognitive building blocks of cooperation", NIH OppNet Workshop on Improving Animal Models of Human Behavioral and Social Processes, Rockville, Maryland

 "Similarity as an alternative to temporal discounting", Quantitative Psychology Program, University of Illinois at Urbana-Champaign

[2013]{.aside}

 "The bounded rationality of self-control", Department of Psychology, Kansas State University

[2015]{.aside}

 "Changing minds: the science of belief", UNL SciComm 2015: A Symposium for Effective Science Communication, University of Nebraska-Lincoln

 "The cognition and evolution of patience", Beta Beta Beta Honor Society, Nebraska Wesleyan University

 "The bounded rationality of cooperation", Workshop on The Costs and Benefits of Information Acquisition and Use in Social Interactions, Arolla, Switzerland

[2016]{.aside}

 "The bounded rationality of reciprocity", Program in Behavior, Economics, and Evolution, University of Lausanne, Switzerland

[2017]{.aside}

 "The bounded rationality of cooperation", Symposium on The Neural Basis of Social Evaluation, Heinrich-Heine-Universität, Düsseldorf, Germany

 "The domain specificity of intertemporal choice in pinyon jays", Messerli Research Institute, University of Veterinary Medicine Vienna, Austria

 "Mesotocin as a hormonal mechanism of social behavior in pinyon jays", Messerli Research Institute, University of Veterinary Medicine Vienna, Austria

[2018]{.aside}

 "The role of opportunity costs in intertemporal choice", Workshop on Economic Behavior of Non-Human Primates, Florence, Italy

[2019]{.aside}

 "The science of belief and decision making", National Environmental Health Association Region IV conference, Omaha, NE

[2020]{.aside}

 "They affect us, we affect them: reciprocal relations between dog and human psychology", Department of Biomedical Sciences and Program in Neuroscience, Iowa State University, Ames, IA

 "They affect us, we affect them: reciprocal relations between dog and human psychology", Anthrozoology Program, Evergreen State College, Olympia, WA \[via Zoom\]

[2022]{.aside}
 
 "Mechanisms of impulsivity in humans and other animals", Cognitive Science Program, University of Arizona, Tucson, AZ

### Conference

[2002]{.aside}

 "The economics of food sharing: when should blue jays cooperate?", **Stevens, J.R.**, and Stephens, Animal Social Complexity and Intelligence Conference, Chicago, IL. (poster)

 "Harassment increases food sharing: a selfish explanation for generosity in primates", Animal Behaviour Society, Bloomington, IN.

[2003]{.aside}

 "The selfish nature of generosity: harassment and food sharing in primates", 4. Göttinger Freilandtage: Cooperation in Primates and Humans, Göttingen, Germany.

[2004]{.aside}

 "The selfish nature of generosity: harassment and food sharing in primates", International Society for Behavioral Ecology, Jyväskylä, Finland.

 "The ecology and evolution of patience in two New World primates", **Stevens, J.R.**, Hallinan, E.V., and Hauser, M.D., Society for the Quantitative Analyses of Behavior, Boston, MA (poster).

 "Quantity discrimination in two callitrichid primate species", **Stevens, J.R.** and Hauser, M.D. Comparative Cognition Conference, Melbourne, FL.

[2005]{.aside}

 "The value of time and space in two New World monkeys", **Stevens, J.R.**, Rosati, A.G., and Hauser, M.D., Comparative Cognition Conference, Melbourne, FL.

[2007]{.aside}

 "Evolutionary origins of patience", Rosati, A.G, **Stevens, J.R.**, Hare, B., and Hauser, M.D., 6. Göttinger Freilandtage: Primate Behavior and Human Universals, Göttingen, Germany.

 "Similarity in intertemporal choice: an outcome and process approach", Society for Judgment and Decision Making Conference, Long Beach, CA (poster).

 "Intertemporal choice in apes and humans", **Stevens, J.R.**, Rosati, A.G, Hare, B., and Hauser, M.D., Subjective Probability, Utility, and Decision Making Conference, Warsaw, Poland.

 "The evolutionary origins of human patience", Rosati, A.G, **Stevens, J.R.**, Hare, B., and Hauser, M.D., Comparative Cognition Conference, Melbourne, FL.

 "Evolving the psychological mechanisms for cooperation", Social Organization and Cognitive Tools Conference, Konrad Lorenz Research Station, Grünau, Austria.

[2008]{.aside}

 "The ecological rationality of risk sensitivity in chimpanzees and bonobos", **Stevens, J.R.**, Rosati, A.G., Heilbronner, S.R., Hare, B., and Hauser, M.D., Comparative Cognition and Learning Meeting, Chicago, IL.

 "The value of waiting and receiving in intertemporal choice", Cokely, E.T, **Stevens, J.R.**, Read, D., and Frederick, S., Society for Judgment and Decision Making Meeting, Chicago, IL (poster).

 "The ecological rationality of patience and risk sensitivity", **Stevens, J.R.**, Rosati, A.G., Heilbronner, S.R., Hare, B., and Hauser, M.D., International Primatological Society Congress, Edinburgh, Scotland.

[2009]{.aside}

 "Expectation and delayed gratification in bonobos", **Stevens, J.R.**, Rosati, A.G., and Heilbronner, S.R., International Ethological Congress, Rennes, France.

 "Models of similarity in intertemporal choice", **Stevens, J.R.**, Cognitive Science Conference, Amsterdam, The Netherlands (poster).

 "Reflections of the social environment in primate minds?", **Stevens, J.R.**, Marewski, J.N., Schooler, L.J., Gilby, I.C., & Wrangham, R.W., The Primate Mind Workshop, Erice, Sicily (poster).

 "Expectation and delayed gratification in bonobos", **Stevens, J.R.**, Rosati, A.G., and Heilbronner, S.R., Comparative Cognition Conference, Melbourne, FL (poster).

[2010]{.aside}

 "Memory interference constrains the emergence of cooperation", **Stevens, J.R.**, Volstorf, J., Schooler, L.J., & Rieskamp, J., Psychonomic Society Meeting, St. Louis, MO.

 "The past predicts the future: patterns of social contact in chimpanzees", **Stevens, J.R.**, Marewski, J.N., Schooler, L.J., Gilby, I.C., & Wrangham, R.W., Comparative Cognition Society Fall Meeting, St. Louis, MO.

 "Models of similarity in intertemporal choice", German Society for Cognitive Science, Potsdam, Germany.

 "Spatial discounting in fish: the convergence of space, time, and number", **Stevens, J.R.**, Schmücking, N., & Reader, S., European Conference on Behavioural Biology, Ferrara, Italy.

 "Memory interference constrains the evolution of cooperation", **Stevens, J.R.**, Volstorf, J., Schooler, L.J., & Rieskamp, J., European Human Behavior and Evolution Conference, Wrocław, Poland.

[2011]{.aside}

 "Spatial discounting of food and social rewards in guppies", Mühlhoff, N., **Stevens, J.R.**, and Reader, S.M., Comparative Cognition Conference, Melbourne, FL.

 "Alternatives to discounting for intertemporal choice", Psychonomic Society Meeting, Seattle, WA.

 "Reproducible results in comparative cognition", Comparative Cognition Society Fall Meeting, Seattle, WA.

[2012]{.aside}

 "Is cooperative memory special? The role of costly errors and context when remembering the past", **Stevens, J.R.** and Winke, T., Psychonomic Society Meeting, Minneapolis, USA.

 "Testing theories of intertemporal choice", Regenwetter, M., **Stevens, J.R.**, Guo, Y., Popova, A., and Zwilling, C., Workshop on Testing Theories of Choice Behavior, Berlin, Germany.

 "Memory for cooperative actions: the role of costly errors and context when remembering the past", **Stevens, J.R.** and Winke, T., Animal Behavior Society--Human Behavior and Evolution Society joint meeting, Albuquerque, NM.

[2013]{.aside}

 "Heuristic and discounting models of intertemporal choice: A quantitative test", Regenwetter, M., **Stevens, J.R.**, Guo, Y., Popova, A., and Zwilling, C., Psychonomic Society Meeting, Toronto, Canada.

 "Time, risk, and environmental decisions", **Stevens, J.R.**, Arthurs, L., and Thurley, A., Society for Judgment and Decision Making Meeting, Toronto, Canada.

 "The psychology of intertemporal choice: concepts and mechanisms", CompCog Workshop on Concepts and Methodologies in the Field of Intertemporal Choices, Vienna, Austria.

 "Wait, there's more: opportunity costs in intertemporal choices", **Stevens, J.R.**, Addessi, E., and Paglieri, F., Comparative Cognition Conference, Melbourne, FL.

[2014]{.aside}

 "Similarity model accounts for magnitude and sign effects in intertemporal choice", **Stevens, J.R.**, Society for Judgment and Decision Making Meeting, Long Beach, CA (poster).

 "The domain specificity of self-control: Caching and intertemporal choice in pinyon jays", **Stevens, J.R.**, Kennedy, B.A., Morales, D. and Burks, M., Psychonomic Society Meeting, Long Beach, CA.

 "The domain specificity of self-control", **Stevens, J.R.**, Kennedy, B.A., Morales, D. and Burks, M., Comparative Cognition Conference, Melbourne, FL.

[2015]{.aside}

 "Similarity judgments of time delay and reward amount in intertemporal choice", **Stevens, J.R.** & Soh, L.-K., Psychonomic Society Meeting, Chicago (poster).

 "The nature of decisions: the influence of natural and built environments on decision making", Johnson, E.L. & **Stevens, J.R.**, Society for Judgment and Decision Making Meeting, Chicago (poster).

[2016]{.aside}

 "Naturally nice and controlled: effects of exposure to nature on stress and decision making", **Stevens, J.R.**, Society for Neuroeconomics Meeting, Berlin (poster).

[2017]{.aside}

 "Judging similarity in intertemporal choice with decision trees", **Stevens, J.R.** & Soh, L.-K., Oklahoma-Kansas Judgment and Decision Making Conference, Norman, OK.

 "Social network structure can buffer costs of forgetting in the evolution of cooperation", **Stevens, J.R.**, Woike, J.K., Schooler, L.J., Lindner, S., & Pachur, T., Comparative Cognition Conference, Melbourne, FL.

 "Mesotocin as a hormonal mechanism of social behavior in pinyon jays", **Stevens, J.R.** & Duque, J.F., European Brain and Behaviour Society, Bilbao, Spain.

 "Order matters: Alphabetizing in-text citations biases citation decisions", **Stevens, J.R.** & Duque, J.F., Psychonomic Society Meeting, Vancouver, Canada.

 "Complex social dynamics and cognition shape cooperation", **Stevens, J.R.**, Göttinger Freilandtage: Social Complexity, Göttingen, Germany.

[2018]{.aside}

 "Order matters: Alphabetizing in-text citations biases citation decisions", **Stevens, J.R.** & Duque, J.F., Oklahoma-Kansas Judgment and Decision Making Conference, Manhattan, KA.

 "Framing patience: how the representation of reward amounts and time delays shapes intertemporal choice", **Stevens, J.R.**, Cully, T., Goh, F., Society for Judgment and Decision Making, New Orleans, LA
(poster).

[2019]{.aside}

 "Social network structure buffers forgetting in cooperative games", **Stevens, J.R.**, Woike, J., Schooler, L.J., Lindner, S., and Pachur, T., Fly Over State Scientists Integrating Evolution (FOSSIL) conference, Stillwater, OK.

 "Dog and owner characteristics predict Canine Good Citizen performance and obedience", **Stevens, J.R.** & Bosworth, M., Canine Science Conference, Phoenix, AZ (poster).

[2021]{.aside}

 "Can Spot go the distance? Owners' predictions of dog impulsivity", **Stevens, J.R.**, Mathias, M., Herridge, M., Duvall, K., & Wolff, L., Comparative Cognition Conference (virtual conference talk).

 "Effects of human-animal interactions on affect and cognition", Thayer, E.R. & **Stevens, J.R.**, International Society for Anthrozoology (virtual conference talk)."

[2022]{.aside}

 "Excluding online data in R with the excluder package", **Stevens, J.R.**, Society for the Improvement of Psychological Science (virtual conference talk).

 "The ManyDogs Project: A big team science approach to canine cognition", **Stevens, J.R.**, International Society for Anthrozoology (virtual conference talk).

### Tutorials

[2013]{.aside}

 "How to use R: An introduction", Department of Psychology, University of Nebraska-Lincoln

 "Why you should use R", CABIN, University of Nebraska-Lincoln

[2015]{.aside}

 "How to use R: An introduction", Department of Psychology, University of Nebraska-Lincoln

[2016]{.aside}

 "How to use R: An introduction", Department of Psychology, University of Nebraska-Lincoln

[2018]{.aside}

 "Towards a robust, transparent, and reproducible science of psychology", CABIN, University of Nebraska-Lincoln

[2019]{.aside}

 "Introduction to Bayes factors", CB3 Club, University of Nebraska-Lincoln

 "Introduction to R Markdown", CB3 Club, University of Nebraska-Lincoln

 "Towards robust, transparent, and reproducible science", Department of Political Science, University of Nebraska-Lincoln

[2020]{.aside}

 "Project management and workflows", CB3 Club, University of Nebraska-Lincoln

[2022]{.aside}

 "Importing and excluding Qualtrics data in R", CB3 Club, University of Nebraska-Lincoln

 "Automatically formating statistics in R Markdown with {papaja}", CB3 Club, University of Nebraska-Lincoln


## Grants and Fellowships

### Completed

[1996]{.aside} 

 Bob Gardner Memorial Research Grant in Biology (\$500---Baylor University)

[2000]{.aside} 

 Animal Behavior Society Student Research Grant, "Manipulative mutualism: the effects of harassment on food sharing\" (\$500)

[2000-2001]{.aside} 

 L.S.B. Leakey Foundation General Grant, "The effects of harassment on food sharing in primates\" (\$10,000)

[2001]{.aside} 

 Alexander P. and Lydia Anderson Fellowship (University of Minnesota), "The behavioral ecology of food sharing\" (\$5,970)

[2002-2003]{.aside} 

 Doctoral Dissertation Fellowship (University of Minnesota), "The behavioral ecology of food sharing\" (\$14,000)

[2003-2006]{.aside} 

 National Institutes of Health NRSA Post-doctoral Fellowship, "Psychological constraints on altruism and reciprocity" (F32-MH067408-01, \$118,000)

[2007]{.aside} 

 Deutsche Forschungsgemeinschaft International Conference and Lecture Trips, "Temporal discounting in humans and apes" (1200 euro or \$1600)

[2008]{.aside} 

 Deutsche Forschungsgemeinschaft International Conference and Lecture Trips, "The ecological rationality of patience and risk sensitivity in *Pan*" (1300 euro or \$2000)

[2009]{.aside} 

 Deutscher Akademischer Austausch Dienst International Conference Trips "Reflections of the social environment in the primate mind?" (775 euro or \$1100)

[2010]{.aside} 

 Deutscher Akademischer Austausch Dienst International Conference Trips "Memory interference constrains the evolution of cooperation" (680 euro or \$815)

[2010-2011]{.aside} 

 Science of Virtue Grant, "The heuristics of virtue: integrating virtue ethics and the science of heuristics" Co-PI with E.T. Cokely, A. Feltz, J.N. Marewski, F. Artinger, N. Fleischhut, M. Keller, and G. Gigerenzer (\$200,000)

[2011-2014]{.aside} 

 National Science Foundation, "A quantitative analysis of heuristics and discounting models of intertemporal choice" Co-PI with Michel Regenwetter (NSF-1062045, \$528,916)

[2012-2013]{.aside} 

 University of Nebraska-Lincoln, Planning Grant for the Pathway to Interdisciplinary Research Centers program, Co-PI with Leilani Arthurs (\$9,989)

[2012-2014]{.aside} 

 University of Nebraska-Lincoln, College of Arts & Science Interdisciplinary Seed Grant, "Environmental decisions in an uncertain world", Co-PI with Leilani Arthurs (\$6,579)

[2013]{.aside} 

 University of Nebraska-Lincoln, Faculty Seed Grant, "Developing an animal model of self-control" (\$9,968)

 European Science Foundation, CompCog Discussion Meeting, "Concepts and methodologies in the field of intertemporal choices", Co-PI with Friederike Range (8,000 euro or \$10,460)

[2014-2016]{.aside} 

 National Science Foundation REU Supplement, "A quantitative analysis of heuristics and discounting models of intertemporal choice" Co-PI with Michel Regenwetter (NSF-1062045, \$6,000)

 Nebraska EPSCoR FIRST Grant, "Hormonal mechanisms of cooperation" (\$19,927)

[2015-2016]{.aside} 

 University of Nebraska-Lincoln, Layman Award, "Hormonal influences on social bonding and cooperation" (\$10,000)

[2016]{.aside} 

 University of Nebraska-Lincoln, College of Arts & Sciences International Travel Award, Society for Neuroeconomics Meeting (\$1,500)

 University of Nebraska-Lincoln, Center for Brain, Biology and Behavior Seed Grant, "Stress as a mediator between exposure to nature and decision making" (\$4,600)

 University of Nebraska Food for Health Collaboration Initiative Planning Grant , "Understanding the effect of exercise on future food intake: The role of behavioral, physiological, and neural mechanisms" Co-PI with Karsten Koehler (PI), Matthew Bice, Ronald Bulbulian, Jeffrey French, Christopher Gustafson, Maital Neta, Scott Stoltenberg (\$20,000)

[2017-2018]{.aside} 

 University of Nebraska-Lincoln, College of Arts & Sciences International Research Collaboration Award, "Oxytocin as a hormonal mechanism of prosociality in dogs and wolves" (\$9,964)

[2017-2019]{.aside} 

 University of Nebraska Food for Health Collaboration Initiative Seed Grant, "Understanding the effect of exercise on future food intake: The role of behavioral, physiological, and neural mechanisms" Co-PI with Karsten Koehler (PI), Matthew Bice, Ronald Bulbulian, Jeffrey French, Christopher Gustafson, Maital Neta, Scott Stoltenberg (\$150,000)

[2018]{.aside} 

 University of Nebraska-Lincoln College of Arts & Sciences Partnership Seed Funding Grant, "Predicting dog training success" (\$9,958)

[2019]{.aside} 

 Great Plains IDeA-CTR Vouchers for Core Facilities, "Exercise and temporal food choices" PI with Karsten Koehler (\$4,400)

[2019-2022]{.aside} 

 Great Plains IDeA-CTR Pilot Program, "Age-related differences in food choices and appetite regulation in the context of exercise\", co-PI with Julie Boron (PI), Karsten Koehler, and Cary Savage (\$73,250)

[2020-2021]{.aside} 

 University of Nebraska-Lincoln Maude Hammond Fling Faculty Research Fellowship, "Assessing numerical discrimination in dogs", PI with Mike Dodd (\$10,000)

### Ongoing

[2017-]{.aside} 

 National Science Foundation, "Similarity as a process model of intertemporal choice" PI with Leen-Kiat Soh (NSF-1658837, \$655,373)

[2021-]{.aside} 

 University of Nebraska Collaboration Initiative Grant, "Enhancing well-being and animal bonds in rural populations", PI with Lisa Karr, Michelle Howell Smith, and Rosemary Strasser (\$7,500)


## Teaching Experience

Teaching assistant, *General Biology, Biol 1009*---Biology, University of Minnesota (1997, 1998)

Teaching assistant, *Introduction to Animal Behavior, EEB 3111*---Ecology, Evolution, and Behavior, University of Minnesota (1998, 1999, 2001)

Teaching assistant, *Behavioral Ecology, EEB 5325/7*---Ecology, Evolution, and Behavior, University of Minnesota (1999, 2000, 2002)

Teaching assistant, *Evolution of Social Behavior, EEB 5321*---Ecology, Evolution, and Behavior, University of Minnesota (2000)

Teaching fellow, *Evolution of Human Nature, Science B-29*---Harvard University (2003)

Teaching fellow, *Animal Cognition Laboratory, Psych 1152r*---Harvard University (2005)

Discussion leader, *Advances in Behavioral Economics*---Harvard University (2005)

Lecturer, *Psychology of Economic Decision Making, Psy 1104*---Harvard University (2006)

Instructor, *Evolution, Behavior, and Society, Psyc 270*---University of Nebraska (2011--2016, 2018, 2020)

Instructor, *Psychology of Decision Making, Psyc 961*---University of Nebraska (2012, 2013, 2015, 2017, 2020, 2022)

Instructor, *Learning Processes, Psyc 461/861*---University of Nebraska (2013--2017)

Instructor, *Perspectives in Psychology, Psyc 440/840*---University of Nebraska (2013--2016, 2018--2020)

Instructor, *Animal Learning & Cognition, Psyc 461/861*---University of Nebraska (2019)

Instructor, *Data Science and Visualization in R*, Psyc 492/971*---University of Nebraska (2021)

Instructor, *Controversial Issues in Psychology*, Psyc 440/840*---University of Nebraska (2022)


## Summer Schools and Workshops

[2007]{.aside} 

 "Evolutionary perspectives on decision making", International Max Planck Research School: LIFE Seminar

[2008]{.aside} 

 "The evolution of ecological rationality", Summer Institute on Bounded Rationality, Berlin, Germany

[2009-2011]{.aside} 

 "Darwinian decision making", Summer Institute on Bounded Rationality, Berlin, Germany

[2016]{.aside} 

 "The psychology of decision making", College of Business Administration Honors Academy Workshop, UNL


## Guest Lectures

[1998]{.aside} 

 "A game theoretical approach to fighting and assessment", University of Minnesota---Evolution of Social Behavior: EEB 5321

[1999-2000]{.aside} 

 "Foraging and territoriality", University of Minnesota---Behavioral Ecology: EEB 5325/7

[1999]{.aside} 

 "Competition and fighting", University of Minnesota---Introduction to Animal Behavior: EEB 3111

[2000-2001]{.aside} 

 "Non-kin cooperation", University of Minnesota---Evolution of Social Behavior: EEB 5321, Introduction to Animal Behavior: Biol 3411

[2002]{.aside} 

 "Cognitive ecology", University of Minnesota---Behavioral Ecology: EEB 5327

 "Careers in animal behavior\", University of Minnesota---Biology Colloquium: Biol 1020

 "The evolution of sex", University of Minnesota---Behavioral Ecology: EEB 5327

[2003]{.aside} 

 "Games people play: human psychology and economics", Mount Ida College---Global Scientific Issues: Natural Sciences 303

 "Cooperative minds: the evolutionary psychology of altruism", Harvard University---Intro. to Psychology: Psych 1

 "Cognitive constraints on reciprocity", Harvard University---Evolution and Social Behavior: Philosophy 252

[2007]{.aside} 

 "Evolutionary perspectives on decision making\", International Max Planck Research School---LIFE Seminar

[2017-2018]{.aside} 

 "Animal intelligence", University of Nebraska-Lincoln---Life in the Universe: Astronomy 117

[2018]{.aside} 

 "Animal cognition", Nebraska Wesleyan University---How Animals Think

[2018-2019]{.aside} 

 "Introduction to dog cognition", Nebraska Wesleyan University---Dogs and People

[2019]{.aside} 

 "Dog cognition", University of Nebraska-Lincoln---Introduction to Companion Animals: Animal Science 251

 "Using machine learning to study decision making", University of Nebraska-Lincoln---Introduction to Informatics: Computer Science and Computer Engineering 100

[2020]{.aside} 

 "Canine-human interaction", University of Nebraska-Lincoln---Fundamentals of Animal Biology and Industry: Animal Science 100

[2021]{.aside} 

 "Reciprocal relations between dog and human psychology", University of Nebraska-Lincoln---Behavioral Neuroscience: Psychology 465


## Theses Advised

### Undergraduate

[2003-2004]{.aside}

 Elizabeth Hallinan---"Temporal discounting in two New World primates, the cotton-top tamarin (*Saguinus oedipus*) and the common marmoset (*Callithrix jacchus*)", (senior thesis, Mind, Brain, and Behavior Program,  Biology, Harvard University)

[2004-2005]{.aside}

 Alexandra Rosati---"Context-dependent discounting in two New World primates, the cotton-top tamarin (*Saguinus oedipus*) and the common marmoset (*Callithrix jacchus*)", (senior thesis, Mind, Brain, and Behavior Program, Psychology, Harvard University) *Winner of Hoopes Thesis Award and Psychology Faculty Award*

[2005-2007]{.aside}

 Sarah Heilbronner---"The evolution of risk-sensitive preferences in nonhuman primates", (senior thesis, Mind, Brain, and Behavior Program, Psychology, Harvard University) *Winner of Psychology Faculty Award*

[2010-2011]{.aside}

 Tim Winke---"The role of costly errors in cooperative memory", (Bachelors thesis, Universität Bayreuth)

[2014-2015]{.aside}

 Whitney Leichner---"Hormonal mechanisms of non-kin cooperation: A study of the effects of mesotocin on prosocial behavior in pinyon jays (*Gymnorhinus cyanocephalus*)", (honor's thesis in Psychology, University of Nebraska-Lincoln)

[2015-2016]{.aside}

 Molly Shane---"Nature's effect on stress and decision making", (honor's thesis in Psychology, University of Nebraska-Lincoln)

 Tyler Stading---"Naturally stressed: The effect of nature exposure on stress physiology and decision making", (honor's thesis in Psychology, University of Nebraska-Lincoln)

[2020]{.aside}

 Hannah Eggert---"General and veterinary care of service dogs and how service dogs benefit their handlers", (honor's thesis in Veterinary Sciences, University of Nebraska-Lincoln)

[2020-2021]{.aside}

 Megan Herridge---"Owner perception of impulsivity in dogs and implementation of as spatial choice task for evaluation", (honor's thesis in Animal Science, University of Nebraska-Lincoln)

 McKenna Yohe---"Predictors of separation anxiety in dogs", (honor's thesis in Veterinary Science and Psychology, University of Nebraska-Lincoln)

### Graduate

[2008-2012]{.aside}

 Jenny Volstorf---"The role of memory in cooperation", (PhD thesis, International Max Planck Research School on Adapting Behavior in a Fundamentally Uncertain World)

[2009-2010]{.aside}

 Nelly Mülhoff--"Spacial discounting of food and social partners in guppies (*Poecilia reticulata*)", (Diploma (Masters) thesis, Humboldt-Universität)

[2012-2019]{.aside}

 Juan Duque---"Patterns of behavioral and physiological consistency in pinyon jays (*Gymnorhinus cyancephalus*)", (PhD thesis, Dept. of Psychology, University of Nebraska-Lincoln)

[2017-2019]{.aside}

 Francine Goh--"Social influences on similarity judgments and intertemporal choice", (Master's thesis, Dept. of Psychology, University of Nebraska-Lincoln)

[2018-2020]{.aside}

 Elise Thayer--"Effects of human-animal interactions on affect and cognition", (Master's thesis, Dept. of Psychology, University of Nebraska-Lincoln)

[2019-2022]{.aside}

 London Wolff--"Friends or food: comparing social and food-based numerical cognition in captive pinyon jays", (Master's thesis, Dept. of Psychology, University of Nebraska-Lincoln)


## Outreach

[2014]{.aside} 

 Volunteer for "Eight-Legged Encounters\" outreach exhibit at Denver Museum of Nature and Science

[2015]{.aside} 

 Stevens, A.N.P. & **Stevens, J.R.** Cool jobs: Getting in your head. *Science News for Students*.

 Invited speaker for UNL SciComm 2015: A Symposium for Effective Science Communication

 Co-Leader "Science Literacy: Applied STEM Reasoning for the 21st Century and Beyond\" project

 Volunteer judge for Morley Elementary Science Fair

[2016]{.aside} 

 Organizer for "Bird Brains" station at BrainStorm event at Sunday with a Scientist at University of Nebraska State Museum

[2018]{.aside} 

 Co-organizer for Animal Behavior event at Sunday with a Scientist at University of Nebraska State Museum

[2018-2019]{.aside} 

 Organizer for Husker DogFest at University of Nebraska-Lincoln

[2019]{.aside} Guest speaker at Edgerton Explorit Dog Science Camp

 Invited speaker for Science Café by University of Nebraska State Museum: \"Pawsitive Psychology: Dog-Human Bonds\"

 Facilitator of Girl Scout Troop 20606 Animal Helpers badge

[2021]{.aside} 
 
 Guest speaker at Edgerton Explorit Veterinary Camp

[2021-2022]{.aside} 
 
 Host for Future Huskers visit


## Professional Service and Development

[1999]{.aside} 

 Participant in TA Web Certification, TAWEB 103---Academic and Distributed Computing Services, Center for Teaching and Learning Services, University of Minnesota

[1999-2000]{.aside} 

 Student representative for departmental seminar committee, Dept. of Ecology, Evolution, and Behavior, University of Minnesota

[1999-2001]{.aside} 

 Student representative for Mechanisms of Behavior faculty search, Dept. of Ecology, Evolution, and Behavior, University of Minnesota

[2000]{.aside} 

 Organizer of the Biological Basis of Behavior Seminar, EEB 8360---Ecology, Evolution, and Behavior, University of Minnesota

 Co-author curriculum for Introduction to Animal Behavior Laboratory, EEB 3411---Ecology, Evolution, and Behavior, University of Minnesota

[2002]{.aside}

 Participant in Preparing Future Faculty Retreat---Preparing Future Faculty, Center for Teaching and Learning Services, University of Minnesota

[2003]{.aside}

 Participant in Fall Teaching Conference---Derek Bok Center for Teaching and Learning, Harvard University

[2004]{.aside}

 Workshop leader for the Mind, Brain, and Behavior Senior Thesis Workshops, Harvard University

[2007]{.aside}

 Organizer for MPI Workshop on Inferences and Preferences in Humans and Other Animals, MPI for Evolutionary Anthropology, Leipzig, Germany

 Co-organizer of Workshop on Lifespan Development of Heuristics and Evolutionary Perspectives, International Max Planck Research School: LIFE

[2008-2011]{.aside}

 Faculty for Summer Institute on Bounded Rationality in Psychology and Economics, Berlin, Germany

[2010]{.aside} 

 Co-organizer (with Christian Agrillo) of symposium on Space, Time, and Number Representation in Animals for European Conference on Behavioural Biology, Ferrara, Italy

[2010-2011]{.aside} 

 Associate researcher in Center for Integrative Life Sciences, Humboldt-Universität, Berlin, Germany

[2010-2017]{.aside} 

 Editor-in-chief of *Frontiers in Comparative Psychology*

 Associate editor of *Frontiers in Psychology*

[2011]{.aside} 

 Co-organizer (with Peter Hammerstein) of Ernst Strüngmann Forum on Evolving the Mechanisms of Decision Making, Frankfurt, Germany

Participant in NESCent working group on How Does Cognition Evolve?

[2011-2012]{.aside} 

 Participant in Research Development Fellows Program, University of Nebraska-Lincoln

[2012]{.aside} 

 Co-organizer (with Michel Regenwetter) of Workshop on Testing Theories of Choice Behavior, Berlin, Germany

[2013]{.aside} 

 Co-organizer (with Friederike Range) of CompCog Workshop on Concepts and Methodologies in the Field of Intertemporal Choices, Vienna, Austria

[2013-2014]{.aside} 

 Participant in NESCent working group on Evolution of Decision Making

[2016]{.aside} 

 Organizer of Nebraska Symposium on Motivation on [Impulsivity: How Time and Risk Influence Decision Making](https://psychology.unl.edu/symposium/recent-symposia/#sym2016), University of Nebraska-Lincoln

[2018-]{.aside}

 Program coordinator of [Neuroscience and Behavior](https://psychology.unl.edu/neuroscience-and-behavior) graduate program, Department of Psychology, University of Nebraska-Lincoln

Department of Psychology Executive Committee, University of Nebraska-Lincoln

[2019]{.aside} 

 Co-organizer of Nebraska Symposium on Motivation on [Nature and Psychology: How the Natural World Shapes Our Cognition](https://psychology.unl.edu/symposium/recent-symposia/#sym2019), University of Nebraska-Lincoln

 Invited speaker for Nebraska Academy for Early Childhood Research Knowledge Seminar, University of Nebraska-Lincoln

[2019-2022]{.aside} 

 Information Technology Systems Committee, University of Nebraska-Lincoln

[2020-]{.aside} 

 Editorial board of [*Animal Behavior and Cognition*](https://animalbehaviorandcognition.org/)

[2022]{.aside} 

 Organizer of Nebraska Symposium on Motivation on [Canine Cognition and the Human Bond](https://psychology.unl.edu/symposium/recent-symposia/#sym2022), University of Nebraska-Lincoln

 Chair of search committee for applied cognitive psychologist, University of Nebraska-Lincoln
 
 Co-director of [ManyDogs Project](http://manydogs.org)
 
 Participant in [Research Leaders Program](https://research.unl.edu/researchleaders/), University of Nebraska-Lincoln


## Honors and Awards

[1996]{.aside} 

 Phi Beta Kappa National Honor Society, Baylor University

 Outstanding Senior in Biology, Baylor University

 Outstanding Senior Thesis in Environmental Studies, Baylor University

[1997]{.aside} 

 School of Biological Sciences Research Assistantship Award, University of Nebraska-Lincoln

[2001]{.aside} 

 College of Biological Sciences Outstanding Teaching Assistant Award, University of Minnesota

[2003]{.aside} 

 Derek Bok Center for Teaching and Learning Certificate of Distinction in Teaching, Harvard University

[2016]{.aside} 

 College of Arts and Sciences Distinguished Teaching Award, University of Nebraska-Lincoln

[2017]{.aside} 

 UNL Parents Association Certificate of Recognition for Contributions to Students, University of Nebraska-Lincoln

[2020]{.aside} 

 Susan J. Rosowski Associate Professorship, University of Nebraska-Lincoln


## Software Development

### excluder

Developer of R package [excluder](https://docs.ropensci.org/excluder/), which facilitates excluding data from Qualtrics data sets.

### flashr

Developer of R package [flashr](https://jeffreyrstevens.github.io/flashr/), which creates flashcards for learning terms and descriptions.

### prereg
Minor contributor to R package [prereg](https://github.com/crsh/prereg), which provides R Markdown templates that facilitate authoring preregistrations of scientific studies in PDF format.

### see
Minor contributor to R package [see](https://easystats.github.io/see/), which provides plotting functions using ggplot2.


## Ad-hoc Referee

*Animal Behavior and Cognition*, *Animal Behaviour*, *Animal Cognition*, *Behavioral and Brain Sciences*, *Behavioral Ecology*, *Behavioral Ecology and Sociobiology*, *Behaviour*, *Behavioural Processes*, *Biology Letters*, *Cognition*, Cognitive Science Society, *Current Biology*, *Current Directions in Psychological Science*, *Ethology*, *Etología*, *Evolutionary Psychology*, *iScience*, *Journal of Behavioral Decision Making*, *Journal of Comparative Psychology*, *Journal of Economic Psychology*,  *Journal of Experimental Psychology: General*, *Journal of Experimental Psychology: Learning, Memory, and Cognition*, *Learning & Behavior*, *Nature Reviews Neuroscience*, *Naturwissenschaften*, *Personality and Social Psychology Review*, *PLoS Biology*, *PLoS ONE*, *Proceedings of the National Academy of Sciences USA*, *Proceedings of the Royal Society of London: Series B*, *Psychonomic Bulletin & Review*, *Review of General Psychology*, *Science*, *Science Advances*, *Scientific Reports*, *Trends in Cognitive Sciences*


## Grant Reviews

### Panels

[2015]{.aside} 

 National Science Foundation, Animal Behavior Doctoral Dissertation
Improvement Grant panel

[2015-2016]{.aside} 

 University of Nebraska-Lincoln Graduate Fellowship panel

[2018-2020]{.aside} 

 Buffett Early Childhood Institute Graduate Scholars panel

[2021-2022]{.aside} 

 National Institutes of Health, Human-Animal Interaction panel

### Ad-hoc Reviews

Economic and Social Research Council (UK), Institute for Advanced Study Berlin, Konrad Lorenz Institute, Leakey Foundation, L'Oreal Foundation, National Science Foundation, Vienna Science and Technology Fund, Wellcome Trust


## Professional Societies

Animal Behavior Society, Comparative Cognition Society, International Society for Behavioral Ecology, Psychonomic Society, Society for Judgment and Decision Making

